branches:
  on:
    - master

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

language: cpp

before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install -y --allow-unauthenticated doxygen graphviz
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

script:
- CXX=g++-6 cmake .
- cmake --build .
- cmake --build . --target package
- find CMakeFiles -name '*.cpp' -delete
- find CMakeFiles -name '*.h' -delete
- cmake --build . --target doc

deploy:
  - provider: script
      skip_cleanup: true
      script: curl -T print_ip-1.0.$TRAVIS_BUILD_NUMBER-x86_64.deb -udimm-git:$BINTRAY_API_KEY "https://api.bintray.com/content/dimm-git/otus-cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-1.0.$TRAVIS_BUILD_NUMBER-x86_64.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
      local-dir: html
      skip-cleanup: true
      github-token: $GH_REPO_TOKEN
      keep-history: true
      verbose: true
